openapi: 3.0.1
info:
  title: Web API
  version: '0.1'
  description: simple web api
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: http://localhost:8080
    description: Local server url
paths:
  /hello/{name}:
    get:
      tags:
        - hello
      summary: say hello
      description: Returns a hello message
      operationId: sayHello
      security: []
      parameters:
        - in: path
          name: name
          description: name
          required: true
          schema:
            type: string
          example: world
      responses:
        '200':
          description: Returns a hello message
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/hello.SayHelloResponse'
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.UnauthorizedError'
              example:
                message: Unauthorized
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/error.InternalServerError'
components:
  schemas:
    hello.SayHelloResponse:
      type: object
      properties:
        message:
          type: string
          description: hello message
          example: hello world
      required:
        - message
    error.UnauthorizedError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
    error.InternalServerError:
      type: object
      properties:
        message:
          type: string
      required:
        - message
