# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from pydantic import BaseModel


class UnauthorizedError(BaseModel):
    message: str


class InternalServerError(BaseModel):
    message: str
