# generated by datamodel-codegen:
#   filename:  openapi.yaml

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, Field


class SayHelloResponse(BaseModel):
    message: Annotated[str, Field(examples=["hello world"])]
    """
    hello message
    """
